server:
  port: 8088

customer-service:
  customer-topic-name: customer

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
#    url: jdbc:postgresql://localhost:5432/bank?currentSchema=card&binaryTransfer=true&reWriteBatchedInserts=true
    url: jdbc:postgresql://db:5432/bank?currentSchema=card&binaryTransfer=true&reWriteBatchedInserts=true
#    url: jdbc:postgresql://host.docker.internal:5432/bank?currentSchema=card&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: B3@gl3
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always
  application:
    name: cards
    profiles:
      active: prod
#  config:
#    import: optional:configserver:http://localhost:8071
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

endpoints:
  shutdown:
    enabled: tue

info:
  app:
    name: Card Service
    description: Bank Application
    version: 1.0.0
